/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CommunityId = IDL.Nat;
export const NotationGameId = IDL.Nat;
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'gamesPlayed' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'rating' : IDL.Nat,
  'draws' : IDL.Nat,
});
export const Time = IDL.Int;
export const Community = IDL.Record({
  'id' : CommunityId,
  'members' : IDL.Vec(IDL.Principal),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
});
export const NotationGame = IDL.Record({
  'id' : NotationGameId,
  'pgn' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
});
export const Post = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'communityId' : CommunityId,
  'createdAt' : Time,
  'author' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCommunity' : IDL.Func([IDL.Text, IDL.Text], [CommunityId], []),
  'createPost' : IDL.Func([CommunityId, IDL.Text, IDL.Text], [], []),
  'deleteNotationGame' : IDL.Func([NotationGameId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunity' : IDL.Func([CommunityId], [Community], ['query']),
  'getNotationGame' : IDL.Func([NotationGameId], [NotationGame], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinCommunity' : IDL.Func([CommunityId], [], []),
  'leaveCommunity' : IDL.Func([CommunityId], [], []),
  'listCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
  'listNotationGames' : IDL.Func([], [IDL.Vec(NotationGame)], ['query']),
  'listPosts' : IDL.Func([CommunityId], [IDL.Vec(Post)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveNotationGame' : IDL.Func([IDL.Text, IDL.Text], [NotationGameId], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CommunityId = IDL.Nat;
  const NotationGameId = IDL.Nat;
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'gamesPlayed' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'rating' : IDL.Nat,
    'draws' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Community = IDL.Record({
    'id' : CommunityId,
    'members' : IDL.Vec(IDL.Principal),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  const NotationGame = IDL.Record({
    'id' : NotationGameId,
    'pgn' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
  });
  const Post = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'communityId' : CommunityId,
    'createdAt' : Time,
    'author' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCommunity' : IDL.Func([IDL.Text, IDL.Text], [CommunityId], []),
    'createPost' : IDL.Func([CommunityId, IDL.Text, IDL.Text], [], []),
    'deleteNotationGame' : IDL.Func([NotationGameId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunity' : IDL.Func([CommunityId], [Community], ['query']),
    'getNotationGame' : IDL.Func([NotationGameId], [NotationGame], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinCommunity' : IDL.Func([CommunityId], [], []),
    'leaveCommunity' : IDL.Func([CommunityId], [], []),
    'listCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
    'listNotationGames' : IDL.Func([], [IDL.Vec(NotationGame)], ['query']),
    'listPosts' : IDL.Func([CommunityId], [IDL.Vec(Post)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveNotationGame' : IDL.Func([IDL.Text, IDL.Text], [NotationGameId], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };