/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Community {
  'id' : CommunityId,
  'members' : Array<Principal>,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
}
export type CommunityId = bigint;
export interface NotationGame {
  'id' : NotationGameId,
  'pgn' : string,
  'title' : string,
  'owner' : Principal,
  'createdAt' : Time,
}
export type NotationGameId = bigint;
export interface Post {
  'title' : string,
  'content' : string,
  'communityId' : CommunityId,
  'createdAt' : Time,
  'author' : Principal,
}
export type Time = bigint;
export interface UserProfile {
  'displayName' : string,
  'gamesPlayed' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'rating' : bigint,
  'draws' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCommunity' : ActorMethod<[string, string], CommunityId>,
  'createPost' : ActorMethod<[CommunityId, string, string], undefined>,
  'deleteNotationGame' : ActorMethod<[NotationGameId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunity' : ActorMethod<[CommunityId], Community>,
  'getNotationGame' : ActorMethod<[NotationGameId], NotationGame>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinCommunity' : ActorMethod<[CommunityId], undefined>,
  'leaveCommunity' : ActorMethod<[CommunityId], undefined>,
  'listCommunities' : ActorMethod<[], Array<Community>>,
  'listNotationGames' : ActorMethod<[], Array<NotationGame>>,
  'listPosts' : ActorMethod<[CommunityId], Array<Post>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveNotationGame' : ActorMethod<[string, string], NotationGameId>,
  'updateDisplayName' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];